### ISSUE TITLE
Hi, can you share the code for the baselines?

### ISSUE THREAD

**Issue by lovian14** [drimpossible/GDumb#1]

**Comment by drimpossible** [comment]
Hi!

This is the code for the GDumb baseline. All other numbers are taken from their respective papers, some of which have the code available alongside for reproduction. 

Does this address the question?

**Comment by drimpossible** [comment]
Closing this issue for now. Please do re-open it if there are further questions in this line.

**Comment by pclucas14** [comment]
Hi, 

congratulations on getting the paper accepted. I was hoping to get more information on the baseline numbers. It seems GDUMB leverages data augmentation, which I don't think was used for the other baselines. Do you have GDUMB numbers without data augmentation ? Currently in the process of adding GDUMB as a baseline in our ICML submission.

edit : I will open a new issue, as you may not be getting notifications for closed ones.
