### ISSUE TITLE
Unclear how to do train/test split

### ISSUE THREAD

**Issue by bennevans** [drimpossible/GDumb#3]
In the README.md it says to "convert [TinyImagenet] to ImageFolder format with train and test splits".

1. Is there code available to do this split? 
2. If not, what is the correct way to handle the split as the test labels are not included from the tiny-imagenet website?

Thanks,
Ben

**Comment by drimpossible** [comment]
Hi,

Ah, we only use the train and val splits -- `val` is renamed to `test`. We do not use the test folder given in TinyImagenet link. 

Does this address the question?

**Comment by bennevans** [comment]
Yes thank you!

**Comment by zeyuanyin** [comment]
TinyImagenet link is invalid

**Comment by drimpossible** [comment]
Hi, the updated link should work now. For reference it should be: https://www.kaggle.com/competitions/tiny-imagenet/data

**Comment by zeyuanyin** [comment]
Thanks, and I find a file that can split the `val`. https://gist.github.com/lromor/bcfc69dcf31b2f3244358aea10b7a11b
